### ISSUE TITLE
请问如何爬取歌曲源文件呀?

### ISSUE THREAD

**Issue by ZengDaWei** [NacedWang/163MusicSpider#3]

**Comment by syaxx0819** [comment]
您好!刚刚收到您的信息,这个项目本身对于网易云音乐的爬取就是不合法的...原本有可以爬取163歌词的,但是后面被网易云发了律师函,就不能爬取了,原来项目的所有者也把这部分功能去掉了...我记得思路是利用网易云音乐的某个歌曲的外部链接进行爬取....也不是记得很清楚了...

在2020-02-25 16:57:25，小曾notifications@github.com写道：

**Comment by NacedWang** [comment]
源文件肯定是不能爬取的
